version: '3.8'

services:
    backend:
        build: ../backend
        container_name: docker-backend
        ports:
            - '5000:5000'
        env_file:
            - ../backend/.env
        volumes:
            - ../backend/uploads:/app/uploads
        restart: always

    frontend:
        build: ../frontend
        container_name: docker-frontend
        ports:
            - '5173:5173'
        volumes:
            - ../frontend/src:/app/src
        depends_on:
            - backend
        restart: always
